datasource-host: localhost
datasource-port: 33061
datasource-username: root
datasource-password: wc123456
datasource-db: simple-codebase


spring:
  datasource:
    url: jdbc:mysql://${datasource-host}:${datasource-port}/${datasource-db}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${datasource-username}
    password: ${datasource-password}
    schema: classpath:sql/schema.sql
    initialization-mode: always
server:
  port: 8089